stages:
    - deploy

variables:
    TAG: $CI_PIPELINE_IID

deploy:dev:
    stage: deploy
    tags:
        - pluto
    rules:
        -   if: $CI_COMMIT_BRANCH == "develop"
    script:
        - echo "\n\n# Variables from .gitlab-ci\n" >> web/.env.production
        - echo "NEXT_PUBLIC_API_URL=https://jispen.uxf.dev" >> web/.env.production

        - docker build -t registry.dev.uxf.cz/jispen/web:${TAG} ./web
        - docker push registry.dev.uxf.cz/jispen/web:${TAG}

        - docker build -t registry.dev.uxf.cz/jispen/api:${TAG} ./api
        - docker push registry.dev.uxf.cz/jispen/api:${TAG}

        - docker build -t registry.dev.uxf.cz/jispen/nginx:${TAG} ./nginx
        - docker push registry.dev.uxf.cz/jispen/nginx:${TAG}

        - docker -H pluto.uxf.cz:2376 --tlsverify stack deploy -c docker-stack.yml jispen-dev --with-registry-auth

