version: '3.8'
services:
    db:
        container_name: jispen-postgres
        image: postgres:14.1-alpine
        env_file:
            - ./database/.env
        volumes:
            - db:/var/lib/postgresql/data

    api:
        container_name: jispen-api
        build:
            context: ./api
        depends_on:
            - db
        links:
            - db

    web:
        container_name: jispen-web
        build:
            context: ./web
        depends_on:
            - api
        links:
            - api

    nginx:
        image: nginx:alpine
        container_name: jispen-nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8008:80"
        depends_on:
            - api
            - web
        restart: on-failure

    adminer:
        image: adminer:latest
        container_name: jispen-adminer
        depends_on:
            - db
        ports:
            - "8080:8080"


volumes:
    db:
        driver: local