version: '3.8'
services:
    db:
        image: postgres:14
        container_name: jispen-postgres
        env_file:
            - ./database/.env
        volumes:
            - db:/var/lib/postgresql/data

    api:
        container_name: jispen-api
        build:
            context: ./api
        depends_on:
            - db
        links:
            - db

    web:
        container_name: jispen-web
        build:
            context: ./web
        depends_on:
            - api
        links:
            - api

    nginx:
        image: nginx:alpine
        container_name: jispen-nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8008:80"
        depends_on:
            - api
            - web
        restart: on-failure

    redis:
        image: redis:7-alpine
        container_name: jispen-redis

volumes:
    db:
        driver: local