version: '3.8'
services:
    api:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./api:/app
        env_file:
            - ./api/.env.local
        command: yarn dev

    web:
        build:
            dockerfile: Dockerfile.dev
        volumes:
            - ./web:/app
        env_file:
            - ./web/.env.local
        command: yarn dev

    db:
        ports:
            - "6543:5432"

    adminer:
        image: adminer:latest
        container_name: jispen-adminer
        depends_on:
            - db
        ports:
            - "8080:8080"

    redis:
        ports:
            - "7480:6379"

volumes:
    api:
    web:
