version: '3.8'
services:
    api:
        build:
            dockerfile: Dockerfile
        command: node src/main.js

    web:
        build:
            dockerfile: Dockerfile
        env_file:
            - ./web/.env
        command: node server.js
