version: '3.8'
services:
    db:
        container_name: jispen-postgres
        image: postgres:14.1-alpine
        env_file:
            - ./database/.env
        volumes:
            - db:/var/lib/postgresql/data
            - ./database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

    api:
        container_name: jispen-api
        build:
            context: ./api
            target: prod
        depends_on:
            - db
        expose:
            - "8000"
        env_file:
            - ./api/.env
        links:
            - db
        command: node main.js

    web:
        container_name: jispen-web
        build:
            context: ./web
            target: prod
        depends_on:
            - api
        expose:
            - "3000"
        env_file:
            - ./web/.env
        links:
            - api
        command: node server.js

    nginx:
        image: nginx:alpine
        container_name: jispen-nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8008:80"
        depends_on:
            - api
            - web


volumes:
    db:
        driver: local